spring.application.name=ApiGateway
server.port=8080

spring.config.import=configserver:http://localhost:15000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[1].id=chat-service
spring.cloud.gateway.routes[1].uri=lb://chat-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/chat/**

spring.cloud.gateway.routes[2].id=i18n-service
spring.cloud.gateway.routes[2].uri=lb://i18n-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/i18n/**
