spring.application.name=user-service
server.port=8082

spring.config.import=configserver:http://localhost:15000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/ycyw_db
spring.datasource.username=ycyw_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true