spring.application.name=chat-service
server.port=8081

spring.config.import=optional:configserver:http://localhost:15000

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Swagger (springdoc)
springdoc.swagger-ui.path=/swagger-ui.html

# PostgreSQL (docker-compose)
# 5433:5432 pour éviter un conflit avec un Postgres local (souvent sur 5432)
spring.datasource.url=jdbc:postgresql://localhost:5433/ycyw_db
spring.datasource.username=ycyw_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false